web:
  build: .
  environment:
    MYENV: TEST_DISCOUNT_CARDS
  volumes:
    - .:/test_discount_cards
web_migrate:
  extends:
    service: web
  command: python manage.py migrate
web_run:
  extends:
    service: web
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"